from . import secret as secret

ENV = {
    "DATABASE_ENGINE": secret.DATABASE_ENGINE,
    "DATABASE_NAME": secret.DATABASE_NAME,
    "DATABASE_USER": secret.DATABASE_USER,
    "DATABASE_PASSWORD": secret.DATABASE_PASSWORD,
    "DATABASE_HOST": secret.DATABASE_HOST,
    "DATABASE_PORT": secret.DATABASE_PORT,
    "DEBUG_MODE": secret.DEBUG_MODE,
    "ALLOWED_HOSTS": secret.ALLOWED_HOSTS,
    "ALLOWED_CIDR_NETS": secret.ALLOWED_CIDR_NETS,
    "GRAPHIQL_MODE": secret.GRAPHIQL_MODE,
}
